In [1]:
import pandas as pd
import numpy as np

In [2]:
train_no_wildtype = pd.read_csv("train_no_wildtype.csv")
train_wildtype_groups = pd.read_csv("train_wildtype_groups.csv")

In [3]:
train_no_wildtype

,seq_id,protein_sequence,pH,data_source,tm,x,group,wildtype
0,0,AAAAKAAALALLGEAPEVVDIWLPAGWRQPFRVFRLERKGDGVLVG...,7.0,doi.org/10.1038/s41592-020-0801-4,75.7,341,-1,NaN
1,1,AAADGEPLHNEEERAGAGQVGRSLPQESEEQRTGSRPRRRRDLGSR...,7.0,doi.org/10.1038/s41592-020-0801-4,50.5,286,-1,NaN
2,2,AAAFSTPRATSYRILSSAGSGSTRADAPQVRRLHTTRDLLAKDYYA...,7.0,doi.org/10.1038/s41592-020-0801-4,40.5,497,-1,NaN
3,3,AAASGLRTAIPAQPLRHLLQPAPRPCLRPFGLLSVRAGSARRSGLL...,7.0,doi.org/10.1038/s41592-020-0801-4,47.2,265,-1,NaN
4,4,AAATKSGPRRQSQGASVRTFTPFYFLVEPVDTLSVRGSSVILNCSA...,7.0,doi.org/10.1038/s41592-020-0801-4,49.5,1451,-1,NaN
...,...,...,...,...,...,...,...,...
24781,31385,YYMYSGGGSALAAGGGGAGRKGDWNDIDSIKKKDLHHSRGDEKAQG...,7.0,doi.org/10.1038/s41592-020-0801-4,51.8,549,-1,NaN
24782,31386,YYNDQHRLSSYSVETAMFLSWERAIVKPGAMFKKAVIGFNCNVDLI...,7.0,doi.org/10.1038/s41592-020-0801-4,37.2,469,-1,NaN
24783,31387,YYQRTLGAELLYKISFGEMPKSAQDSAENCPSGMQFPDTAIAHANV...,7.0,doi.org/10.1038/s41592-020-0801-4,64.6,128,-1,NaN
24784,31388,YYSFSDNITTVFLSRQAIDDDHSLSLGTISDVVESENGVVAADDAR...,7.0,doi.org/10.1038/s41592-020-0801-4,50.7,593,-1,NaN
24785,31389,YYVPDEYWQSLEVAHKLTFGYGYLTWEWVQGIRSYVYPLLIAGLYK...,7.0,doi.org/10.1038/s41592-020-0801-4,37.6,537,-1,NaN

In [4]:
train_wildtype_groups

,seq_id,protein_sequence,pH,data_source,tm,x,group,wildtype
0,18020,MNAFEMLRIDERLRLKIYKDTEGYYTIGIGHLLTKSPSLNAAKSEL...,2.0,10.1021/bi00535a054,38.1,164,0,MNIFEMLRIDERLRLKIYKDTEGYYTIGIGHLLTKSPSLNAAKSEL...
1,18021,MNAFEMLRIDERLRLKIYKDTEGYYTIGIGHLLTKSPSLNAAKSEL...,4.2,NaN,53.3,164,0,MNIFEMLRIDERLRLKIYKDTEGYYTIGIGHLLTKSPSLNAAKSEL...
2,18022,MNAFEMLRIDERLRLKIYKDTEGYYTIGIGHLLTKSPSLNAAKSEL...,2.0,10.1038/334406a0,38.1,164,0,MNIFEMLRIDERLRLKIYKDTEGYYTIGIGHLLTKSPSLNAAKSEL...
3,18023,MNAFEMLRIDERLRLKIYKDTEGYYTIGIGHLLTKSPSLNAAKSEL...,6.5,10.1038/334406a0,62.9,164,0,MNIFEMLRIDERLRLKIYKDTEGYYTIGIGHLLTKSPSLNAAKSEL...
4,18060,MNCFEMLRIDERLRLKIYKDTEGYYTIGIGHLLTKSPSLNAAKSEL...,2.0,NaN,41.9,164,0,MNIFEMLRIDERLRLKIYKDTEGYYTIGIGHLLTKSPSLNAAKSEL...
...,...,...,...,...,...,...,...,...
4190,5092,MALEKSLVRLLLLVLILLVLGWVQPSLGKESAAKKFQRQHMDSDSS...,5.0,10.1093/protein/15.11.887,56.4,156,77,MALEKSLVRLLLLVLILLVLGWVQPSLGKESRAKKFQRQHMDSDSS...
4191,5093,MALEKSLVRLLLLVLILLVLGWVQPSLGKESRAAKFQRQHMDSDSS...,5.0,10.1093/protein/15.11.887,55.9,156,77,MALEKSLVRLLLLVLILLVLGWVQPSLGKESRAKKFQRQHMDSDSS...
4192,5094,MALEKSLVRLLLLVLILLVLGWVQPSLGKESRAKKFERQHMDSDSS...,5.0,10.1093/protein/15.11.887,54.5,156,77,MALEKSLVRLLLLVLILLVLGWVQPSLGKESRAKKFQRQHMDSDSS...
4193,5095,MALEKSLVRLLLLVLILLVLGWVQPSLGKESRAKKFQRQHMDSDNS...,5.0,10.1093/protein/15.11.887,53.2,156,77,MALEKSLVRLLLLVLILLVLGWVQPSLGKESRAKKFQRQHMDSDSS...
4194,5096,MALEKSLVRLLLLVLILLVLGWVQPSLGKESRAKKFQRQHMDSGSS...,5.0,10.1093/protein/15.11.887,54.4,156,77,MALEKSLVRLLLLVLILLVLGWVQPSLGKESRAKKFQRQHMDSDSS...

In [5]:
train_wildtype_groups["wildtype"][0]

'MNIFEMLRIDERLRLKIYKDTEGYYTIGIGHLLTKSPSLNAAKSELDKAIGRNCNGVITKDEAEKLFNQDVDAAVRGILRNAKLKPVYDSLDAVRRCALINMVFQMGETGVAGFTNSLRMLQQKRWDEAAVNLAKSIWYNQTPNRAKRVITTFRTGTWDAYKNL'

In [6]:
"""
1. Load revised train CSV
2. Measure mean tm, set wildtype temperature as mean tm, then delta tm as wildtype tm - mutant tm
3. Partition to train/test
4. Create bigram features of wildtype and mutant on both train/test data
5. Train model using bigrams to predict delta tm 
6. Measure correlation of prediction on test data
"""

'\n1. Load revised train CSV\n2. Measure mean tm, set wildtype temperature as mean tm, then delta tm as wildtype tm - mutant tm\n3. Partition to train/test\n4. Create bigram features of wildtype and mutant on both train/test data\n5. Train model using bigrams to predict delta tm \n6. Measure correlation of prediction on test data\n'

In [8]:
train_df = pd.read_parquet("train_df.parquet")

In [9]:
train_df.columns

Index(['protein_sequence', 'pH', 'data_source', 'tm'], dtype='object')

In [10]:
mean_tm = train_df["tm"].mean()

In [ ]:
from sklearn.model_selection import train_test_split
train_df, test_df = train_test_split(df, test_size=0.33, random_state=42)